spring:
  main:
    allow-circular-references : true
  application:
    name: walterWhiteJournal
  data:
    mongodb:
      database: journalDb
      auto-index-creation: true
server:
  port: 8080
#  servlet:
#    context-path: /walterWhiteJournal

