spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: gs005220@gmail.com
    password: aqia gcbb vyuw pmnb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: mongodb+srv://gauravsingh950400:SQY1j6CwnT8Yhkmx@cluster0.i6qi5z6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  profiles:
    active: dev

textToSpeech:
  api:
    key: sk_2c3592bcbe4781cf95fa0edb02c2464d92e642b366e72d3e


