spring:
  data:
    mongodb:
      uri: mongodb+srv://********:*******@cluster0.i6qi5z6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  profiles:
    active: dev

quote:
  api:
    key: ***************

textToSpeech:
  api:
    key: ****************
#logging:
#  level:
#    com.journal.walterWhiteJournal.service.UserServices: OFF


#  servlet:
#    context-path: /walterWhiteJournal

