spring:
  redis:
    uri: redis-cli -u redis://default:DqVZwEgii45kApchxauqk35HdaZ5J69Q@redis-12244.c305.ap-south-1-1.ec2.redns.redis-cloud.com:12244
  main:
    allow-circular-references : true
  application:
    name: walterWhiteJournal
  data:
    mongodb:
      database: journalDb
      auto-index-creation: true
server:
  port: 8080
#  servlet:
#    context-path: /walterWhiteJournal

